classDiagram
  class ChangeKind
  class ChangedFilesTree
  class ChangedFilesTreeProps
  class DiffRow
  class DiffTableRow
  class DiffWorkspace
  class DiffWorkspaceProps
  class DirNode
  class ElectronAPI
  class FileChange
  class FileDiffPayload
  class FileNode
  class InsightsColumn
  class InsightsColumnProps
  class LlmSettings
  class LlmSettingsModal
  class LlmSettingsModalProps
  class LlmSummarizePayload
  class LlmSummaryMarkdown
  class LlmSummaryMarkdownProps
  class MetricPill
  class SidebarNav
  class SidebarNavProps
  class TreeRow