classDiagram
  class ChangeKind
  class ChangedFilesTree
  class ChangedFilesTreeProps
  class CodeCityFileNode
  class CodeCityFilters
  class CodeCityLayoutResult
  class CodeCityLegend
  class CodeCityModel
  class CodeCityOwnershipSummary
  class CodeCityRenderableBuilding
  class CodeCityRenderableDistrict
  class CodeCitySymbolNode
  class CodeCityView
  class CodebaseOutline
  class DiffRow
  class DiffSelectionLineRange
  class DiffSelectionSymbolMatch
  class DiffSymbolSpan
  class DiffTableRow
  class DiffWorkspace
  class DiffWorkspaceProps
  class DirNode
  class DocWorkspaceMetrics
  class DocumentationWorkspace